# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 618)
        MainWindow.setStyleSheet("background-color:darkred;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lblBaslik = QtWidgets.QLabel(self.centralwidget)
        self.lblBaslik.setStyleSheet("color:white;\n"
"font-weight:bold;")
        self.lblBaslik.setObjectName("lblBaslik")
        self.gridLayout.addWidget(self.lblBaslik, 0, 0, 1, 1)
        self.txtBaslik = QtWidgets.QLineEdit(self.centralwidget)
        self.txtBaslik.setStyleSheet("background-color:white;\n"
"font-weight:bold;")
        self.txtBaslik.setObjectName("txtBaslik")
        self.gridLayout.addWidget(self.txtBaslik, 0, 1, 1, 1)
        self.txtMesaj = QtWidgets.QTextEdit(self.centralwidget)
        self.txtMesaj.setStyleSheet("background-color:white;\n"
"font-weight:bold;")
        self.txtMesaj.setObjectName("txtMesaj")
        self.gridLayout.addWidget(self.txtMesaj, 1, 1, 1, 1)
        self.lblMesaj = QtWidgets.QLabel(self.centralwidget)
        self.lblMesaj.setStyleSheet("color:white;\n"
"font-weight:bold;")
        self.lblMesaj.setObjectName("lblMesaj")
        self.gridLayout.addWidget(self.lblMesaj, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("background-color:lightgrey;\n"
"color:white;\n"
"font-weight:bold;\n"
"border-radius:10px;\n"
"padding:15px;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblBaslik.setText(_translate("MainWindow", "BAŞLIK"))
        self.lblMesaj.setText(_translate("MainWindow", "MESAJI YAZ"))
        self.pushButton.setText(_translate("MainWindow", "EMAİL GÖNDER"))
